### ISSUE TITLE
Sockets invalid listen arguement

### ISSUE THREAD

**Issue by elitekode2** [Minds/sockets#1]
![screen shot 2018-06-07 at 1 12 50 pm](https://user-images.githubusercontent.com/36805232/41115152-a400b05c-6a54-11e8-8fc3-3906ee7bfaa5.png)

Im trying to add sockets to my minds development build. Can anybody help out with this error?

**Comment by Serkan-devel** [comment]
Can you copy-paste the output here? I'm unable to read it on my phone.
Preferably between `<pre>` and `</pre> for proper formatting..

**Comment by Serkan-devel** [comment]
Not that they've removed the repo for a while due to private keys stored on it

**Comment by elitekode2** [comment]
<pre>
`docker run -t minds/sockets     -e CASSANDRA_KEYSPACE='minds'     -e CASSANDRA_SERVERS='127.0.0.1'     -e JWT_SECRET='keepsave-and-match-settings.php'     -e PORT='8010'     -e REDIS_HOST='redis-host'     -e REDIS_PORT='6379'
process.env.PORT undefined
process.env.PORT undefined
process.env.PORT true
process.env.PORT true
net.js:1496
  throw new Error('Invalid listen argument: ' + util.inspect(options));
  ^

Error: Invalid listen argument: { port: true }
    at Server.listen (net.js:1496:9)
    at Function.listen (/node_modules/express/lib/application.js:618:24)
    at new IO (/build/src/core/io/io.js:13:32)
    at di_1.Di.bind (/build/src/core/io/provider.js:7:16)
    at Function.get (/build/src/core/di/di.js:10:66)
    at MindsSocketServer.initBindings (/build/src/server.js:35:27)
    at MindsSocketServer.init (/build/src/server.js:21:14)
    at Object.<anonymous> (/build/index.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)`
</pre>

**Comment by elitekode2** [comment]
Can anybody help out with this?

**Comment by Serkan-devel** [comment]
You're not the only one getting no response Minds/minds#77

**Comment by ottman** [comment]
Please be patient we have limited resources and will be focusing on the
open source more later this year after we hit the mainnet blockchain. You
aren't being intentionally ignored. We are aware of the issues
